#!/bin/bash
echo "=> Building discord"
docker run --rm \
    -v "$PWD":/usr/src/mcdiscord \
    -w /usr/src/mcdiscord \
    -e GOOS=linux \
    -e GOARCH=amd64 \
    golang:latest \
    bash hooks/pre_build_build.sh
